# Generated by Django 3.0.3 on 2020-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_based_engine', '0002_auto_20200228_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp_rules',
            name='status',
            field=models.BooleanField(),
        ),
    ]
