# Generated by Django 3.0.3 on 2020-02-29 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_based_engine', '0003_auto_20200228_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='camp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(max_length=20)),
                ('metric', models.CharField(max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='camp_rules',
            name='Start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
