# Generated by Django 3.0.3 on 2020-03-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_based_engine', '0004_auto_20200301_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp_rules',
            name='Start_time',
        ),
        migrations.AlterField(
            model_name='camp_rules',
            name='action',
            field=models.CharField(default='notify', max_length=10),
        ),
        migrations.AlterField(
            model_name='camp_rules',
            name='campaign',
            field=models.CharField(choices=[('camp1', 'zomato'), ('camp2', 'flipkart'), ('camp3', 'amazon'), ('camp4', 'swiggy'), ('camp5', 'grofer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='camp_rules',
            name='condition',
            field=models.CharField(choices=[('rule1', '`eCPM` >= $5.00 AND `Impressions` >= 1000000'), ('rule2', '`Spend` >= $1000.00 AND `eCPC` <=  $0.20'), ('rule3', '`Clicks` >= 50000 AND `Installs` <= 100'), ('rule4', '`eCPI` >= $2.00 AND `Installs` >= 100')], max_length=50),
        ),
    ]
