# Generated by Django 3.0.3 on 2020-03-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_based_engine', '0005_auto_20200302_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp_rules',
            name='schedule_time',
            field=models.CharField(choices=[('min_15', 'every 15 min'), ('hour_1', 'every hour'), ('day_1', 'every day')], max_length=20),
        ),
    ]
