# Generated by Django 3.0.3 on 2020-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_based_engine', '0006_auto_20200302_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp_rules',
            name='campaign',
            field=models.CharField(choices=[('zomato', 'zomato'), ('flipkart', 'flipkart'), ('amazon', 'amazon'), ('swiggy', 'swiggy'), ('grofer', 'grofer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='camp_rules',
            name='condition',
            field=models.CharField(choices=[('`eCPM` >= $5.00 AND `Impressions` >= 1000000', '`eCPM` >= $5.00 AND `Impressions` >= 1000000'), ('`Spend` >= $1000.00 AND `eCPC` <=  $0.20', '`Spend` >= $1000.00 AND `eCPC` <=  $0.20'), ('`Clicks` >= 50000 AND `Installs` <= 100', '`Clicks` >= 50000 AND `Installs` <= 100'), ('`eCPI` >= $2.00 AND `Installs` >= 100', '`eCPI` >= $2.00 AND `Installs` >= 100')], max_length=50),
        ),
        migrations.AlterField(
            model_name='camp_rules',
            name='schedule_time',
            field=models.CharField(choices=[('every 15 min', 'every 15 min'), ('every hour', 'every hour'), ('every day', 'every day')], max_length=20),
        ),
    ]
